//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string UID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Role { get; set; }
        public string CentreID { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
    
        private CostCentre CostCentre { get; set; }
        private Role Role1 { get; set; }
        private Title Title1 { get; set; }
    }
}
