//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Duty
    {
        public string DutyID { get; set; }
        public string StaffID { get; set; }
        public Nullable<double> Hours { get; set; }
        public string CourseType { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> AmountOF_UNITA { get; set; }
        public Nullable<int> AmountOF_HQ { get; set; }
        public Nullable<int> AmountOF_HQPT { get; set; }
        public Nullable<int> AmountOF_L { get; set; }
        public Nullable<int> AmountOF_T { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
